name: Hello workflow

on: [push]

jobs:
  say_hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: make say-hello
